apiVersion: apps/v1
kind: Deployment
metadata:
  name: skiapp-deployment
  namespace: team-riker
spec:
  selector:
    matchLabels:
      app: skiapp
  replicas: 1
  template:
    metadata:
      labels:
        app: skiapp
    spec:
      containers:
      - name: skiapp
        image: sharepointoscar/skiapp:v2
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: '50Mi'
            cpu: '50m'
          limits:
            memory: '50Mi'
            cpu: '50m'